/* eslint-disable react-hooks/rules-of-hooks */
import React, { useState, useRef } from "react";
import Head from "next/head";
import emailjs from "@emailjs/browser";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "../../components/footer";
import NavBar from "../../components/mainHeader";

type Props = {};

const feedBack = (props: Props) => {
  const form: any = useRef();

  const handleSubmit = (e: any) => {
    e.preventDefault();

    emailjs
      .sendForm(
        process.env.NEXT_PUBLIC_YOUR_SERVICE_ID || "",
        process.env.NEXT_PUBLIC_YOUR_TEMPLATE_ID || "",
        form.current,
        process.env.NEXT_PUBLIC_YOUR_PUBLIC_KEY || ""
      )
      .then(
        (result) => {
          toast.success("Feedback Sent Successfully !", {
            position: toast.POSITION.TOP_RIGHT,
          });
          e.target.reset();
        },
        (error) => {
          toast.error("Error Sending Feedback !", {
            position: toast.POSITION.TOP_RIGHT,
          });
          e.target.reset();
        }
      );
  };

  return (
    <>
      <Head>
        <title>Welcome to Omdena&apos;s Collaborator Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/OmdenaFavicon.png" />
      </Head>

      <NavBar />

      <section className="bg-white dark:bg-gray-900">
        <div className="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
          <div className="mr-auto place-self-center lg:col-span-7">
            <h1 className="max-w-2xl mb-4 text-4xl font-extrabold leading-none md:text-5xl xl:text-6xl dark:text-white">
              Report an issue
            </h1>
          </div>
        </div>
      </section>

      <section className="bg-gray-50 dark:bg-gray-800">
        <div className="max-w-screen-xl px-4 py-8 mx-auto sm:py-16 lg:px-6">
          <div className="mb-8 max-w-full-md lg:mb-16">
            <div className="flex items-center justify-center p-12">
              <div className="mx-auto w-full max-w-[550px]">
                <form ref={form} onSubmit={handleSubmit}>
                  <div className="mb-5">
                    <label className="block mb-3 text-base font-medium text-white">
                      Email Address
                    </label>
                    <input
                      type="email"
                      name="from_email"
                      required
                      placeholder="example@domain.com"
                      className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    />
                  </div>
                  <div className="mb-5">
                    <label className="block mb-3 text-base font-medium text-white">
                      Any of your data missing?
                    </label>
                    <textarea
                      rows={4}
                      name="missing_data"
                      required
                      placeholder="Type your message"
                      className="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    ></textarea>
                  </div>
                  <div className="mb-5">
                    <label className="block mb-3 text-base font-medium text-white">
                      Any bugs to report?
                    </label>
                    <textarea
                      rows={4}
                      name="bugs_report"
                      required
                      placeholder="Type your message"
                      className="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    ></textarea>
                  </div>
                  <div className="mb-5">
                    <label className="block mb-3 text-base font-medium text-white">
                      Feedback
                    </label>
                    <textarea
                      rows={4}
                      name="feedback"
                      required
                      placeholder="Type your message"
                      className="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    ></textarea>
                  </div>
                  <div className="mb-5">
                    <label className="block mb-3 text-base font-medium text-white">
                      Comments?
                    </label>
                    <textarea
                      rows={4}
                      name="comments"
                      required
                      placeholder="Type your message"
                      className="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                    ></textarea>
                  </div>
                  <div>
                    <button className="hover:shadow-form rounded-md bg-[#6A64F1] py-3 px-8 text-base font-semibold text-white outline-none">
                      Submit
                    </button>
                  </div>
                  <ToastContainer />
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
};

export default feedBack;
