import type { NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import Image from "next/image";
import Footer from "../../components/footer";
import NavBar from "../../components/mainHeaderPrivate";
import styles from "../styles/Home.module.css";
import mainGraphic from "../../Assets/omdenabg.png";
import omdenaLore from "../../Assets/omdenaLore.png";
import aws from "../../Assets/aws.svg";
import azure from "../../Assets/azure.svg";
import dagshub from "../../Assets/dagshub.png";
import withAuth from "../../HOC/withAuth";

const Home: NextPage = () => {
  const handleLogout = () => {
    Router.push("/");
  };

  const handleRegister = () => {
    Router.push("/auth/register");
  };

  const myLoader = () => {
    return `https://flowbite.s3.amazonaws.com/blocks/marketing-ui/hero/phone-mockup.png`;
  };

  const myLoader2 = () => {
    return `https://flowbite.s3.amazonaws.com/blocks/marketing-ui/content/office-long-2.png`;
  };
  const myLoader3 = () => {
    return `https://flowbite.s3.amazonaws.com/blocks/marketing-ui/content/office-long-2.png`;
  };
  const myLoader4 = () => {
    return `https://flowbite.com/docs/images/logo.svg`;
  };
  const myLoader5 = () => {
    return `https://flowbite.com/docs/images/logo.svg`;
  };

  return (
    <>
      <Head>
        <title>Welcome to Omdena&apos;s Collaborator Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/OmdenaFavicon.png" />
      </Head>

      <NavBar />

      <section className="bg-white dark:bg-gray-900">
        <div className="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
          <div className="mr-auto place-self-center lg:col-span-7">
            <h1 className="max-w-2xl mb-4 text-4xl font-extrabold leading-none md:text-5xl xl:text-6xl dark:text-white">
              Resources
            </h1>
          </div>
        </div>
      </section>

      <section className="bg-gray-50 dark:bg-gray-800">
        <div className="max-w-screen-xl px-4 py-8 mx-auto sm:py-16 lg:px-6">
          <div className="mb-8 max-w-full-md lg:mb-16">
            <iframe
              className="airtable-embed"
              src="https://airtable.com/embed/shrd4EtLZkXkmdHlK?backgroundColor=blue&viewControls=on"
              frameBorder="0"
              width="100%"
              height="533"
            ></iframe>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
};

export default withAuth(Home);
