import React, { useState, useEffect } from "react";
import Head from "next/head";
import axios from "axios";
import jwt_decode from "jwt-decode";
import NavBar from "../../components/mainHeaderPrivate";
import Footer from "../../components/footer";
import CollaboratorProfileChapter from "../../components/profiles/chapter";
import GuestUserChapter from "../../components/chapter/guest";

type Props = {};

const ChapterProfile = (props: Props) => {
  const [isSSR, setIsSSR] = useState(true);
  const [data, setData] = useState([]);
  const [session, setSession] = useState("Collaborator");

  useEffect(() => {
    setIsSSR(false);
  }, []);

  useEffect(() => {
    const token: any = localStorage.getItem("accessToken");
    const tokenParsed = JSON.parse(token || "");
    const decodedToken: any = jwt_decode(token);
    const userRole = decodedToken.userData.role;

    const config: any = {
      headers: {
        authorization: tokenParsed,
      },
    };

    if (userRole === "Guest") {
      setSession("Guest");
    }

    if (!isSSR) {
      const getData = async () => {
        const response = await axios.get("/api/profile/user", config);
        setData(response.data.user);
      };
      getData();
    }
  }, [isSSR]);
  return (
    <>
      <Head>
        <title>Welcome to Omdena&apos;s Collaborator Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/OmdenaFavicon.png" />
      </Head>

      <NavBar />

      {session === "Collaborator" || session === "Local Chapter" ? (
        <CollaboratorProfileChapter />
      ) : (
        <GuestUserChapter />
      )}

      <Footer />
    </>
  );
};

export default ChapterProfile;
