import React from "react";
import Head from "next/head";
import Router from "next/router";
import Image from "next/image";
import Footer from "../../components/footer";
import NavBar from "../../components/mainHeaderPrivate";
import collaborators from "../../Assets/collaborators.png";
import withAuth from "../../HOC/withAuth";
import Paths from "../../components/Paths";

type Props = {};

const findOpportunities = (props: Props) => {
  return (
    <>
      <Head>
        <title>Welcome to Omdena&apos;s Collaborator Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/OmdenaFavicon.png" />
      </Head>

      <NavBar />

      <section className="bg-white dark:bg-gray-900">
        <div className="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
          <div className="mr-auto place-self-center lg:col-span-7">
            <h1 className="max-w-2xl mb-4 text-4xl font-extrabold leading-none md:text-5xl xl:text-4xl dark:text-white">
              Find the perfect opportunity to grow your career
            </h1>
            <p className="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
              Omdena has tons of opportunities for its collaborators to grow
              their careers. <br />
              <br />
              This section helps you to find the opportunity that caters to your
              interest. Follow the career path icon below to see the open and
              upcoming opportunities.
            </p>
          </div>
          <div className="hidden lg:mt-0 lg:col-span-5 lg:flex">
            <Image src={collaborators} alt="mockup" width={370} height="400" />
          </div>
        </div>
      </section>

      <section className="bg-white dark:bg-gray-800">
        <div className="items-center max-w-screen-xl gap-16 px-4 py-8 mx-auto lg:grid lg:grid-cols-1 lg:py-16 lg:px-6">
          <div className="font-light text-gray-500 sm:text-lg dark:text-gray-400">
            <h2 className="mb-4 text-4xl font-extrabold text-center text-gray-900 dark:text-white">
              Find the perfect opportunity to grow your career
            </h2>
            <div className="grid grid-cols-2 gap-8 text-center sm:gap-12 md:grid-cols-3 lg:grid-cols-4">
              <a
                className="flex items-center justify-center wow fadeInUp"
                data-wow-duration="1s"
                href="https://omdena.com/projects"
              >
                <div className="px-12 py-8 mb-12 transition duration-300 ease-in-out transform border-b border-gray-100 bg-gray-50 hover:-translate-y-2">
                  <div className="inline-block mb-4 text-gray-900">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="2rem"
                      height="2rem"
                      fill="currentColor"
                      className="bi bi-search"
                      viewBox="0 0 16 16"
                    >
                      <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                    </svg>
                  </div>
                  <h3 className="mb-2 text-lg font-semibold leading-normal text-black">
                    Become a Researcher
                  </h3>
                </div>
              </a>

              <a
                className="flex items-center justify-center wow fadeInUp"
                data-wow-duration="1s"
                data-wow-delay=".1s"
                href="https://airtable.com/shrSKqls39xnculVm"
              >
                <div className="px-12 py-8 mb-12 transition duration-300 ease-in-out transform border-b border-gray-100 bg-gray-50 hover:-translate-y-2">
                  <div className="inline-block mb-4 text-gray-900">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="2rem"
                      height="2rem"
                      fill="currentColor"
                      className="bi bi-chat-square-dots"
                      viewBox="0 0 16 16"
                    >
                      <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"></path>
                      <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"></path>
                    </svg>
                  </div>
                  <h3 className="mb-2 text-lg font-semibold leading-normal text-black">
                    Become a Engineering Lead
                  </h3>
                </div>
              </a>

              <a
                className="flex items-center justify-center wow fadeInUp"
                data-wow-duration="1s"
                href="https://omdena.com/chapters/"
              >
                <div className="px-12 py-8 mb-12 transition duration-300 ease-in-out transform border-b border-gray-100 bg-gray-50 hover:-translate-y-2">
                  <div className="inline-block mb-4 text-gray-900">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="2rem"
                      height="2rem"
                      fill="currentColor"
                      className="bi bi-card-checklist"
                      viewBox="0 0 16 16"
                    >
                      <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"></path>
                      <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z"></path>
                    </svg>
                  </div>
                  <h3 className="mb-2 text-lg font-semibold leading-normal text-black">
                    Become a Community Lead
                  </h3>
                </div>
              </a>

              <a
                className="flex items-center justify-center wow fadeInUp"
                data-wow-duration="1s"
                href="https://omdena.com/omdena-school/"
              >
                <div className="px-12 py-8 mb-12 transition duration-300 ease-in-out transform border-b border-gray-100 bg-gray-50 hover:-translate-y-2">
                  <div className="inline-block mb-4 text-gray-900">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="2rem"
                      height="2rem"
                      fill="currentColor"
                      className="bi bi-search"
                      viewBox="0 0 16 16"
                    >
                      <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                    </svg>
                  </div>
                  <h3 className="mb-2 text-lg font-semibold leading-normal text-black">
                    Become a Product Lead
                  </h3>
                </div>
              </a>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-white dark:bg-gray-900">
        <div className="max-w-screen-xl px-4 py-8 mx-auto sm:py-16 lg:px-6">
          <div className="max-w-screen-sm mx-auto text-center">
            <h2 className="mb-4 text-4xl font-extrabold leading-tight text-gray-900 dark:text-white">
              Career Path Development Platform
            </h2>
            <p className="mb-6 font-light text-gray-500 dark:text-gray-400 md:text-lg">
              Our 4 impact career paths for you
            </p>
            <h2 className="mb-4 text-xl font-bold leading-tight text-gray-900 dark:text-white">
              Depending on your interest and skill, you can follow one or more
              of the 4 paths.
            </h2>
            <Paths />
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
};

export default withAuth(findOpportunities);
