import React, { useState, useEffect } from "react";
import Image from "next/image";
import Head from "next/head";
import axios from "axios";
import jwt_decode from "jwt-decode";
import Footer from "../../components/footer";
import NavBar from "../../components/mainHeaderPrivate";
import RemoveButton from "../../components/removeButton";
import AddButton from "../../components/addButton";
import withAuth from "../../HOC/withAuth";
import NameSkeleton from "../../components/Skeletons/Name";
import Points from "../../components/Skeletons/Points";
import CollaboratorSchoolProfile from "../../components/school/collaborator";
import GuestSchoolProfile from "../../components/school/guest";

type Props = {};

const SchoolProfile = (props: Props) => {
  const [isSSR, setIsSSR] = useState(true);
  const [data, setData] = useState([]);
  const [session, setSession] = useState("Collaborator");

  useEffect(() => {
    setIsSSR(false);
  }, []);

  useEffect(() => {
    const token: any = localStorage.getItem("accessToken");
    const tokenParsed = JSON.parse(token || "");
    const decodedToken: any = jwt_decode(token);
    const userRole = decodedToken.userData.role;

    const config: any = {
      headers: {
        authorization: tokenParsed,
      },
    };

    if (userRole === "Guest") {
      setSession("Guest");
    }

    if (!isSSR) {
      const getData = async () => {
        const response = await axios.get("/api/school/user", config);
        setData(response.data.user);
      };
      getData();
    }
  }, [isSSR]);

  return (
    <>
      <Head>
        <title>Welcome to Omdena&apos;s Collaborator Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/OmdenaFavicon.png" />
      </Head>

      <NavBar />

      {session === "Collaborator" ? (
        <CollaboratorSchoolProfile />
      ) : (
        <GuestSchoolProfile />
      )}

      <Footer />
    </>
  );
};

export default withAuth(SchoolProfile);
